function re=Htb(parameters)
vf=parameters.vf;
NN=parameters.NN;
a0=parameters.a0;
sigma0=parameters.sigma0;
sigmax=parameters.sigmax;
sigmay=parameters.sigmay;
sigmaz=parameters.sigmaz;
bM1=parameters.bM1;
bM2=parameters.bM2;
T0=parameters.T0;
T1=parameters.T1;
Tm1=parameters.Tm1;
theta=parameters.theta;
kb=parameters.kb;
kt=parameters.kt;
ilist=1:NN;
jlist=1:NN;
[imat,jmat]=meshgrid(ilist,jlist);
banddiff=spdiags(ones(NN),-1,NN,NN)-spdiags(ones(NN),1,NN,NN);
kxmat=kron(banddiff,speye(NN));
kymat=kron(speye(NN),banddiff);
Hb=vf*(-1i/(2*a0)*kron(kxmat,(cos(theta/2)*sigma0-1i*sigmaz*sin(theta/2))*sigmax)...
       -1i/(2*a0)*kron(kymat,(cos(theta/2)*sigma0-1i*sigmaz*sin(theta/2))*sigmay)...
       -kron(speye(NN^2),(cos(theta/2)*sigma0-1i*sigmaz*sin(theta/2))*(kb(1)*sigmax+kb(2)*sigmay)));
Ht=vf*(-1i/(2*a0)*kron(kxmat,(cos(theta/2)*sigma0+1i*sigmaz*sin(theta/2))*sigmax)...
       -1i/(2*a0)*kron(kymat,(cos(theta/2)*sigma0+1i*sigmaz*sin(theta/2))*sigmay)...
       -kron(speye(NN^2),(cos(theta/2)*sigma0+1i*sigmaz*sin(theta/2))*(kt(1)*sigmax+kt(2)*sigmay)));
expmat1=exp(-1i*(bM1(1)*a0*imat+bM1(2)*a0*jmat)).';
expmat2=exp(-1i*(bM2(1)*a0*imat+bM2(2)*a0*jmat)).';
T=kron(speye(NN^2),T0)+kron(spdiags(expmat1(:),0,NN^2,NN^2),T1)...
    +kron(spdiags(expmat2(:),0,NN^2,NN^2),Tm1);
re=[Hb,T;T',Ht];
end